[build]
command = "npm install --legacy-peer-deps && npm run build"
pages_build_output_dir = "dist"

[build.environment]
NODE_VERSION = "18"

[env.production]
VITE_APP_ENV = "production"
VITE_API_URL = "https://backendggh.vercel.app"
VITE_ENABLE_ADMIN_FEATURES = "true"
VITE_ENABLE_PUBLIC_ACCESS = "true"
