# Wrangler configuration for Cloudflare Pages
name = "ggh-frontend"
compatibility_date = "2024-03-11"

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[env.production.vars]
VITE_APP_ENV = "production"
VITE_API_URL = "https://backendggh.vercel.app"
VITE_ENABLE_ADMIN_FEATURES = "true"
VITE_ENABLE_PUBLIC_ACCESS = "true"
