# Wrangler configuration for Cloudflare Pages
name = "ggh-frontend"
compatibility_date = "2024-03-11"

[build]
command = "npm install && npm run build"
output_directory = "dist"

[env.production]
NODE_VERSION = "18"
VITE_APP_ENV = "production"
VITE_API_URL = "https://backendggh.vercel.app"
VITE_ENABLE_ADMIN_FEATURES = "true"
VITE_ENABLE_PUBLIC_ACCESS = "true"
