[build]
command = "npm install --omit=dev && npm run build"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-11"

[build.environment]
NODE_VERSION = "18"
NODE_ENV = "production"

[env.production]
VITE_APP_ENV = "production"
VITE_API_URL = "https://backendggh.vercel.app"
VITE_ENABLE_ADMIN_FEATURES = "true"
VITE_ENABLE_PUBLIC_ACCESS = "true"
